# Generated by Django 4.0.4 on 2022-04-29 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_catelllgory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Catelllgory',
        ),
    ]
