# Generated by Django 4.0.4 on 2022-05-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_page_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_type',
            field=models.IntegerField(choices=[(1, 'Page'), (2, 'Category'), (3, 'Link')], default=1),
        ),
    ]
