# Generated by Django 4.0.4 on 2022-05-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='section',
            field=models.CharField(default='', max_length=200),
        ),
    ]
